# Generated by Django 5.2.10 on 2026-01-14 13:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InboundEventModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trace_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payload', models.JSONField()),
                ('type', models.CharField(max_length=255)),
                ('queue', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('HANDLED', 'Handled'), ('FAILED', 'Failed')], default='PENDING', max_length=255)),
            ],
            options={
                'db_table': 'events_inbound',
            },
        ),
        migrations.CreateModel(
            name='OutboundEventModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trace_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payload', models.JSONField()),
                ('type', models.CharField(max_length=255)),
                ('queue', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PUBLISHED', 'Published'), ('FAILED', 'Failed')], default='PENDING', max_length=255)),
            ],
            options={
                'db_table': 'events_outbound',
            },
        ),
    ]
